const openBtn=document.querySelector('#menu_btn');const closeBtn=document.querySelector('#close_btn');const ulItems=document.querySelector("nav .container ul");const links=document.querySelectorAll("nav .container ul li");const navConainer=document.querySelector("nav .container");openBtn.addEventListener("click",()=>{ulItems.style.display="flex";openBtn.style.display="none";closeBtn.style.display="inline-block"})
closeBtn.addEventListener("click",()=>{ulItems.style.display="none";openBtn.style.display="inline-block";closeBtn.style.display="none"})
document.onclick=function(e){if(!navConainer.contains(e.target)&&!openBtn.contains(e.target)){ulItems.style.display="none";closeBtn.style.display="none";openBtn.style.display="inline-block"}}
function hideMenu(){ulItems.style.display="none";closeBtn.style.display="none";openBtn.style.display="inline-block"}
links.forEach(link=>{link.addEventListener("click",hideMenu)})
window.addEventListener('resize',()=>{if(window.innerWidth>"1024"){ulItems.style.display="flex";links.forEach(link=>{link.removeEventListener("click",hideMenu)})}});window.addEventListener('resize',()=>{if(window.innerWidth<="1024"){ulItems.style.display="none";openBtn.style.display="inline-block"}});window.addEventListener('click',()=>{if(window.innerWidth>"1024"){ulItems.style.display="flex";ulItems.style.width="26%"}});window.addEventListener("scroll",()=>{document.querySelector("nav").classList.toggle("box_shodow",window.scrollY>0)})
var swiper=new Swiper(".mySwiper",{scrollbar:{el:".swiper-scrollbar",hide:!0,draggable:!0,},autoplay:{delay:5000,disableOnInteraction:!1,},});let myForm=document.getElementById("myForm");let popup=document.getElementById("popup");let close_popup=document.getElementById("close_btn");myForm.addEventListener("submit",function(e){e.preventDefault();popup.classList.add("open_popup");var params={name:document.getElementById("name").value,email:document.getElementById("email").value,phone:document.getElementById("phone").value,message:document.getElementById("message").value};emailjs.send("service_4syirpq","template_6yjkdds",params).then(res=>{document.getElementById("name").value="";document.getElementById("email").value="";document.getElementById("phone").value="";document.getElementById("message").value="";console.log(res)}).catch(error=>console.log(error))})
close_popup.addEventListener("click",()=>{popup.classList.remove("open_popup")})
const navLinks=document.querySelectorAll(".nav_link");const sections=document.querySelectorAll("section");let currentSection="";window.addEventListener("scroll",()=>{sections.forEach(section=>{if(window.scrollY>=(section.offsetTop-section.clientHeight/3)){currentSection=section.id}})
navLinks.forEach(link=>{if(link.href.includes(currentSection)){document.querySelector(".active").classList.remove("active");link.classList.add("active")}})})
const showMore=document.querySelector(".info .read_more");const showContent=document.querySelector(".info .read_more_content");showMore.addEventListener("click",()=>{showContent.classList.toggle("show_and_hide_content");if(showContent.classList.contains("show_and_hide_content")){showMore.textContent="Show Less"}else{showMore.textContent="Show More"}})
const skilItems=document.querySelectorAll(".skills .skill");skilItems.forEach(skill=>{skill.querySelector(".head").addEventListener("click",()=>{skill.querySelector(".items").classList.toggle("show_items")})})
const yearSpan=document.getElementById("currentYear");const newTime=new Date();yearSpan.innerText=newTime.getFullYear()